#!/bin/bash

cat <<EOF
package postgres_backend

//autogenerated

var MigrationTuples = make(map[string]string)

func init() {
EOF
for f in `find migrations -iname "*.sql"`; do
    printf '        MigrationTuples["'
    tmp=`basename $f .sql`
    printf ${tmp:11:20}
    printf '"] = `'
    cat $f
    printf '`\n'
done

printf "}\n"
